#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 24 18:59:51 +0000 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim z80_memory_tb_behav -key {Behavioral:sim_1:Functional:z80_memory_tb} -tclbatch z80_memory_tb.tcl -view /home/user/Z80_Drop_In_2026/z80_memory_tb_behav.wcfg -log simulate.log"
xsim z80_memory_tb_behav -key {Behavioral:sim_1:Functional:z80_memory_tb} -tclbatch z80_memory_tb.tcl -view /home/user/Z80_Drop_In_2026/z80_memory_tb_behav.wcfg -log simulate.log

